quotes/quoteapp/urls.py
from django.urls import path

from . import views

app_name = "quoteapp"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="main_paginate"),
    path("author/<str:author_name>", views.author_detail, name="author_detail"),
    path("tag/<str:tag_name>/", views.quotes_by_tag, name="quotes_by_tags"),
    path(
        "tag/<str:tag_name>/page/<int:page>/",
        views.quotes_by_tag,
        name="quotes_by_tags_paginate",
    ),
    path("quote/", views.quote, name="quote"),
    path("add-author/", views.author, name="author"),
    path("scrap/", views.scrap, name="scrap"),
]

quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quoteapp.urls")),
    path("users/", include("users.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quotes/users/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/quoteapp/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)


class Scrap_url(models.Model):
    url = models.URLField()

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, URLField

from .models import Quote, Author, Scrap_url


class QuoteForm(ModelForm):
    quote = CharField()

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50)
    born_location = CharField(max_length=150)
    description = CharField()

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class ScrapForm(ModelForm):
    # url = URLField(required=True)

    class Meta:
        model = Scrap_url
        exclude = ["url"]

quotes/quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect

from .forms import QuoteForm, AuthorForm, ScrapForm
from .models import Tag, Quote, Author
from .utils import Scrap


def get_top_tags():
    top_tags = Tag.objects.annotate(num_quotes=Count("quote")).order_by("-num_quotes")[
        :10
    ]
    font_sizes = [28, 26, 26, 24, 22, 14, 10, 8, 8, 6]
    for i, tag in enumerate(top_tags):
        tag.font_size = font_sizes[i]
    return top_tags


def main(request, page=1):
    top_tags = get_top_tags()
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(
        request,
        "quoteapp/index.html",
        context={"quotes": quotes_on_page, "top_tags": top_tags},
    )


def quotes_by_tag(request, tag_name, page=1):
    top_tags = get_top_tags()
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(
        request,
        "quoteapp/tag.html",
        {"tag": tag, "quotes": quotes_on_page, "top_tags": top_tags},
    )


def author_detail(request, author_name):
    author = get_object_or_404(Author, fullname=author_name)
    return render(request, "quoteapp/author_detail.html", context={"author": author})


@login_required
def quote(request):
    tags = Tag.objects.all()
    all_authors = Author.objects.all()
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            new_quote.author = Author.objects.get(id=request.POST.get("author"))
            new_quote.save()

            return redirect(to="quoteapp:main")
        else:
            return render(
                request,
                "quoteapp/quote.html",
                {"tags": tags, "all_authors": all_authors, "form": form},
            )

    return render(
        request,
        "quoteapp/quote.html",
        {"tags": tags, "all_authors": all_authors, "form": QuoteForm()},
    )


@login_required
def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            new_author.save()

            return redirect(to="quoteapp:main")
        else:
            return render(
                request,
                "quoteapp/author.html",
                {"form": form},
            )

    return render(
        request,
        "quoteapp/author.html",
        {"form": AuthorForm()},
    )


@login_required()
def scrap(request):
    if request.method == "POST":
        form = ScrapForm(request.POST)
        if form.is_valid():
            scrapper = Scrap()
            url = "http://quotes.toscrape.com/"
            scrapper.run(url)

            return redirect(to="quoteapp:main")
        else:
            return render(
                request,
                "quoteapp/scrap.html",
                {"form": form},
            )

    return render(
        request,
        "quoteapp/scrap.html",
        {"form": ScrapForm()},
    )

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Adding author</h1>
<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Fullname:</strong>
            </label>
        </div>
        <div class="col mb-3">
            <div>{{ form.fullname }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Born date:</strong>
            </label>
            <div>{{ form.born_date }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Born location:</strong>
            </label>
            <div>{{ form.born_location }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Description:</strong>
            </label>
            <div>{{ form.description }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/author_detail.html
{% extends "quoteapp/base.html" %} {% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quotes to Homework</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/bootstrap.min.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/main.css' %}">
</head>
<body>
<div class="container">
    <div class="row header-box">
        <div class="col-md-4">
            <h1>
                <a href="{% url 'quoteapp:main' %}" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            {% if user.is_authenticated %}
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a class="btn nav-link px-2 link-light" href="{% url 'quoteapp:quote' %}">Add new quote</a></li>
                <li><a class="btn nav-link px-2 link-light" href="{% url 'quoteapp:author' %}">Add new author</a></li>
                <li><a class="btn nav-link px-2 link-light" href="{% url 'quoteapp:scrap' %}">Scrap</a></li>
            </ul>
            {% endif %}
        </div>

        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <span>
                Welcome <b>{{ user.username }}!</b>
            </span>
                <a href="{% url 'users:logout' %}">
                    <button type="button" class="btn btn-danger"> Logout</button>
                </a>
                {% else %}
                <a href="{% url 'users:signup' %}">
                    <button type="button" class="btn btn-primary">SignUp</button>
                </a>
                <a href="{% url 'users:login' %}">
                    <button type="button" class="btn btn-primary"> Login</button>
                </a>
                {% endif %}
            </p>
        </div>
    </div>

    <div class="row">

        {% block content %}
        {% endblock %}


        {% block top_ten_tags %}
        {% endblock %}
    </div>
</div>
<footer class="footer">
    <div class="container">
        <p class="text-muted">
            Quotes by: <a href="https://github.com/maxafanasiev">Max Afanasiev</a>
        </p>
        <p class="copyright">
            Made with <span class="zyte">❤</span> by <a class="zyte"
                                                        href="https://https://github.com/maxafanasiev">Max</a>
        </p>
    </div>
</footer>

quotes/quoteapp/templates/quoteapp/index.html
{% extends "quoteapp/base.html" %} {% block content %}

<div class="col-md-8">
{% for quote in quotes %}
<div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">{{ quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags.all %}
        <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
        {% endfor %}


    </div>
</div>

{% endfor %}

<nav>
    <ul class="pager">
        {% if quotes.has_previous %}
        <li class="previous">
            <a href="{% url 'quoteapp:main_paginate' quotes.previous_page_number %}">
                <span aria-hidden="true">←</span> Previous
            </a>
        </li>
        {% endif %}
        {% if quotes.has_next %}
        <li class="next">
            <a href="{% url 'quoteapp:main_paginate' quotes.next_page_number %}">Next
                <span aria-hidden="true">→</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
</div>
{% endblock %}


<!--TOP TEN TAGS BLOCK-->
{% block top_ten_tags %}
<div class="col-md-4 tags-box">
<h2>Top Ten tags</h2>

{% for tag in top_tags %}
<span class="tag-item">
    <a class="tag" style="font-size:{{tag.font_size}}px" href="/tag/{{tag.name}}">{{tag.name}}</a>
</span>
{% endfor %}
</div>
{% endblock %}

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Adding quote</h1>
<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Quote:</strong>
            </label>
            <div>{{ form.quote }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text-light"><strong>Quote author:</strong></label>
        </div>
         <div class="mb-3 col">
            <select name="author">
                {% for author in all_authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text-light"><strong>Select tags:</strong></label>
        </div>
        <div class="mb-3 col">
            <select name="tags" class="form-select" size="5">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/scrap.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Scrapping "http://quotes.toscrape.com/"</h1>
<form method="POST" action="{% url 'quoteapp:scrap' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <div>{{ form.url }}</div>
            {% if form.errors.url %}
            <span class="text-warning"><small>{{ form.errors.url }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Scrape</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %} {% block content %}

<div class="col-md-8">
    <h3>Viewing tag: <a href="/tag/{{tag.name}}/page/1/">{{tag.name}}</a></h3>
{% for quote in quotes %}
<div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">{{ quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
    <div class="tags">
        Tags:
        {% for tag in quote.tags.all %}
        <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
        {% endfor %}


    </div>
</div>

{% endfor %}

<nav>
    <ul class="pager">
        {% if quotes.has_previous %}
        <li class="previous">
            <a href="{% url 'quoteapp:quotes_by_tags_paginate' tag.name quotes.previous_page_number %}">
                <span aria-hidden="true">←</span> Previous
            </a>
        </li>
        {% endif %}
        {% if quotes.has_next %}
        <li class="next">
            <a href="{% url 'quoteapp:quotes_by_tags_paginate' tag.name quotes.next_page_number %}">Next
                <span aria-hidden="true">→</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
</div>
{% endblock %}


<!--TOP TEN TAGS BLOCK-->
{% block top_ten_tags %}
<div class="col-md-4 tags-box">
<h2>Top Ten tags</h2>

{% for tag in top_tags %}
<span class="tag-item">
    <a class="tag" style="font-size:{{tag.font_size}}px" href="/tag/{{tag.name}}">{{tag.name}}</a>
</span>
{% endfor %}
</div>
{% endblock %}