quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quoteapp.urls")),
    path("users/", include("users.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quotes/users/urls.py
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/users/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default="default_avatar.png", upload_to="profile_images")

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    email = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    password1 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

quotes/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to="noteapp:main")
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="users:login")
        else:
            render(request, "users/signup.html", context={"form": form})
            print("not_valid")

    return render(request, "users/signup.html", context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to="quoteapp:main")
    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="quoteapp:main")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to="quoteapp:main")


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"

quotes/users/templates/users/login.html
{% extends "quoteapp/base.html" %} {% block content %}

{% if messages %}
<div xmlns:users="http://www.w3.org/1999/xhtml" xmlns:users="http://www.w3.org/1999/xhtml">
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Username</label>
            <div>{{ form.username }}</div>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Password</label>
            <div>{{ form.password }}</div>
        </div>
    </div>
    <input type="submit" value="Login" class="btn btn-primary">
    <div class="row">
        <div class="form-group col-xs-3">
            <a href=" {% url "users:password_reset" %} " class="text-center"><i>Forgot Password?</i></a>
        </div>
    </div>

</form>

{% endblock %}

quotes/users/templates/users/password_reset.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="post">
    <h2>Password reset</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <div class="row">
        <button type="submit" class="btn btn-primary">Request password reset</button>
    </div>

</form>


{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "quoteapp/base.html" %}

{% block content %}
<div class="row">
    <h2>Password reset complete!</h2>
</div>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "quoteapp/base.html" %}

{% block content %}


<form method="post">
    <h2>Enter new password</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <div class="row">
        <button type="submit" class="btn btn-primary">Save new password</button>
    </div>

</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div class="row">
    <h2>Password reset request sent</h2>
    <p>We've emailed you with instructions on how to reset your password.</p>
</div>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
\{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/users/templates/users/signup.html
{% extends "quoteapp/base.html" %}
{% block content %}

<form action="{% url 'users:signup' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Username</label>
            <div>{{ form.username }}</div>
        </div>
        {% if form.errors.username %}
        <span class="text-warning"><small>{{ form.errors.username }}</small></span>
        {% endif %}
    </div>

    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label"> Email:</label>
            <div>{{ form.email }}</div>
        </div>
        {% if form.errors.email %}
        <span class="text-warning"><small>{{ form.errors.email }}</small></span>
        {% endif %}
    </div>

    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Password</label>
            <div>{{ form.password1 }}</div>
        </div>
        {% if form.errors.password1 %}
        <span class="text-warning"><small>{{ form.errors.password1 }}</small></span>
        {% endif %}
    </div>
    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Confirm password</label>
            <div>{{ form.password2 }}</div>
        </div>
        {% if form.errors.password2 %}
        <span class="text-warning"><small>{{ form.errors.password2 }}</small></span>
        {% endif %}
    </div>
    <input type="submit" value="Login" class="btn btn-primary">

</form>

{% endblock %}